name: Autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose tests set
        required: true
        default: smoke
        type: choice
        options:
          - all
          - smoke
          - critical
          - high
          - medium
          - low

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Clones your code into the working environment

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Run flake8
        run: flake8

      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true

      - name: Run critical tests
        if: "github.event.inputs.deployment_target == 'critical'"
        run: pytest -m critical --alluredir=allure-results
        continue-on-error: true

      - name: Run high tests
        if: "github.event.inputs.deployment_target == 'high'"
        run: pytest -m high --alluredir=allure-results
        continue-on-error: true

      - name: Run medium tests
        if: "github.event.inputs.deployment_target == 'medium'"
        run: pytest -m medium --alluredir=allure-results
        continue-on-error: true

      - name: Run low tests
        if: "github.event.inputs.deployment_target == 'low'"
        run: pytest -m low --alluredir=allure-results
        continue-on-error: true

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Install Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.tgz && sudo tar -zxvf allure-2.33.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.33.0/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: allure generate -c allure-results -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 1
